# ===================================================================
#                     knife4j文档配置
# ===================================================================
knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: 2545946621@qq.com
    concat: zzy
    url: https://github.com/aut-rain
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.itheima.mp.controller
