# ===================================================================
#                     日志配置
# ===================================================================logging:
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss