# ===================================================================
#                     主配置文件
# ===================================================================
spring:
  application:
    name: mp-demo
    description: mybatis-plus-demo
  config:
    import:
      - "classpath:config/application-db.yml"
      - "classpath:config/application-log.yml"
      - "classpath:config/application-swagger.yml"